"""add unit type in reorder item

Revision ID: 07877df74a5c
Revises: 92a114d47418
Create Date: 2026-01-31 12:28:27.746373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07877df74a5c'
down_revision: Union[str, None] = '92a114d47418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reorder_request_items', sa.Column('unit_type', sa.Enum('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reorder_request_items', 'unit_type')
    # ### end Alembic commands ###
