"""add missing unittype enum values

Revision ID: 0f36729d4fa7
Revises: 69326dc6ee30
Create Date: 2025-11-08 18:13:40.296874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f36729d4fa7'
down_revision: Union[str, None] = '69326dc6ee30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing enum values
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'G'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'MG'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'ML'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'CM'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'MM'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'IN'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'BAG'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'BOX'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'CARTON'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'BTL'")
    op.execute("ALTER TYPE unittype ADD VALUE IF NOT EXISTS 'DOZEN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
