"""add unit type in stock level

Revision ID: 1409984d9c52
Revises: d5edf544850c
Create Date: 2026-02-03 15:17:45.631118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1409984d9c52'
down_revision: Union[str, None] = 'd5edf544850c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_levels', sa.Column('unit_type', sa.Enum('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'), nullable=True))
    op.alter_column('stock_movements', 'unit_type',
               existing_type=postgresql.ENUM('PCS', 'KG', 'M2', 'M3', 'L', 'LM', 'G', 'MG', 'ML', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'unit_type',
               existing_type=postgresql.ENUM('PCS', 'KG', 'M2', 'M3', 'L', 'LM', 'G', 'MG', 'ML', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'),
               nullable=False)
    op.drop_column('stock_levels', 'unit_type')
    # ### end Alembic commands ###
