"""add inventory mismatch table

Revision ID: 198d2a659f9c
Revises: 697b9ee8ea74
Create Date: 2025-10-01 19:20:59.696273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198d2a659f9c'
down_revision: Union[str, None] = '697b9ee8ea74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_mismatch_reasons',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_mismatch_reasons')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_mismatch_reasons_name'))
    )
    op.create_index(op.f('ix_inventory_mismatch_reasons_id'), 'inventory_mismatch_reasons', ['id'], unique=False)
    op.add_column('inventory_count_items', sa.Column('reason_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_inventory_count_items_reason_id_inventory_mismatch_reasons'), 'inventory_count_items', 'inventory_mismatch_reasons', ['reason_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_count_items_reason_id_inventory_mismatch_reasons'), 'inventory_count_items', type_='foreignkey')
    op.drop_column('inventory_count_items', 'reason_id')
    op.drop_index(op.f('ix_inventory_mismatch_reasons_id'), table_name='inventory_mismatch_reasons')
    op.drop_table('inventory_mismatch_reasons')
    # ### end Alembic commands ###
