"""add unit type in movement & inventory count item

Revision ID: 213c039ee73c
Revises: c9873439802e
Create Date: 2026-02-01 18:28:31.384369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213c039ee73c'
down_revision: Union[str, None] = 'c9873439802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_count_items', sa.Column('unit_type', sa.Enum('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'), nullable=False))
    op.add_column('stock_movements', sa.Column('unit_type', sa.Enum('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'unit_type')
    op.drop_column('inventory_count_items', 'unit_type')
    # ### end Alembic commands ###
