"""update selling price and remove unit type from product

Revision ID: 244d062746c2
Revises: 935675deff8e
Create Date: 2025-10-25 13:06:41.601680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '244d062746c2'
down_revision: Union[str, None] = '935675deff8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('products', 'unit_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_type', postgresql.ENUM('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='product_unit_type'), autoincrement=False, nullable=False))
    op.alter_column('products', 'selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
