"""Update location type to enum

Revision ID: 2dee77981768
Revises: ef2393bc40d7
Create Date: 2025-10-05 19:10:00.861053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dee77981768'
down_revision: Union[str, None] = 'ef2393bc40d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'location_type',
               existing_type=postgresql.ENUM('BRANCH', 'WAREHOUSE', name='location_type'),
               type_=sa.Enum('WAREHOUSE', 'BRANCH', 'CENTRAL_KITCHEN', name='location_type'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'location_type',
               existing_type=sa.Enum('WAREHOUSE', 'BRANCH', 'CENTRAL_KITCHEN', name='locationtype'),
               type_=postgresql.ENUM('BRANCH', 'WAREHOUSE', name='location_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
