"""add item ingredient table

Revision ID: 49f35e6ca2f2
Revises: fcba8ce3521b
Create Date: 2025-10-30 15:28:33.593196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49f35e6ca2f2'
down_revision: Union[str, None] = 'fcba8ce3521b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_ingredients',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_type', postgresql.ENUM('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_item_id'], ['items.id'], name=op.f('fk_item_ingredients_ingredient_item_id_items')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_ingredients_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_ingredients'))
    )
    op.create_index(op.f('ix_item_ingredients_id'), 'item_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_item_ingredients_ingredient_item_id'), 'item_ingredients', ['ingredient_item_id'], unique=False)
    op.create_index(op.f('ix_item_ingredients_item_id'), 'item_ingredients', ['item_id'], unique=False)
    op.alter_column('approval_members', 'action_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('approval_settings', 'module',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('approval_settings', 'action_type',
               existing_type=postgresql.ENUM('SHIFT', 'SALARY', 'DAYOFF', name='approvalrequesttype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_settings', 'action_type',
               existing_type=postgresql.ENUM('SHIFT', 'SALARY', 'DAYOFF', name='approvalrequesttype'),
               nullable=True)
    op.alter_column('approval_settings', 'module',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('approval_members', 'action_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_item_ingredients_item_id'), table_name='item_ingredients')
    op.drop_index(op.f('ix_item_ingredients_ingredient_item_id'), table_name='item_ingredients')
    op.drop_index(op.f('ix_item_ingredients_id'), table_name='item_ingredients')
    op.drop_table('item_ingredients')
    # ### end Alembic commands ###
