"""add unit type in transfer item

Revision ID: 599685e491ca
Revises: b12e17972c61
Create Date: 2026-01-31 17:39:26.770636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '599685e491ca'
down_revision: Union[str, None] = 'b12e17972c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_items', 'unit_type',
               existing_type=postgresql.ENUM('PCS', 'KG', 'M2', 'M3', 'L', 'LM', 'G', 'MG', 'ML', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'),
               nullable=False)
    op.add_column('transfer_items', sa.Column('unit_type', sa.Enum('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_items', 'unit_type')
    op.alter_column('product_items', 'unit_type',
               existing_type=postgresql.ENUM('PCS', 'KG', 'M2', 'M3', 'L', 'LM', 'G', 'MG', 'ML', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'),
               nullable=True)
    # ### end Alembic commands ###
