"""update warehouse location to reorder request

Revision ID: 697b9ee8ea74
Revises: d1c09da1ee4e
Create Date: 2025-09-30 17:05:37.890079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697b9ee8ea74'
down_revision: Union[str, None] = 'd1c09da1ee4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reorder_requests', sa.Column('to_location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_reorder_requests_to_location_id_locations'), 'reorder_requests', 'locations', ['to_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reorder_requests_to_location_id_locations'), 'reorder_requests', type_='foreignkey')
    op.drop_column('reorder_requests', 'to_location_id')
    # ### end Alembic commands ###
