"""add reorder request id in transer

Revision ID: 72ff3fe30846
Revises: 1409984d9c52
Create Date: 2026-02-05 12:27:43.707105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ff3fe30846'
down_revision: Union[str, None] = '1409984d9c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('reorder_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_transfers_reorder_request_id_reorder_requests'), 'transfers', 'reorder_requests', ['reorder_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transfers_reorder_request_id_reorder_requests'), 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'reorder_request_id')
    # ### end Alembic commands ###
