"""update approval member module

Revision ID: 7af364156609
Revises: e9c1362a6105
Create Date: 2025-10-13 18:19:48.704710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af364156609'
down_revision: Union[str, None] = 'e9c1362a6105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_approval_members_module', 'approval_members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_approval_members_module', 'approval_members', ['module'])
    # ### end Alembic commands ###
