"""add manager in lcation

Revision ID: 8abf7884fc2a
Revises: 0f36729d4fa7
Create Date: 2025-11-18 18:28:34.164404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abf7884fc2a'
down_revision: Union[str, None] = '0f36729d4fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_locations_manager_id_users'), 'locations', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_locations_manager_id_users'), 'locations', type_='foreignkey')
    op.drop_column('locations', 'manager_id')
    # ### end Alembic commands ###
