"""add payment condition, file path columns

Revision ID: 8d8ca6683206
Revises: d0d91f4aaae0
Create Date: 2025-09-22 17:17:50.328027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8ca6683206'
down_revision: Union[str, None] = 'd0d91f4aaae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('payment_conditions', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'file_path')
    op.drop_column('purchase_orders', 'payment_conditions')
    # ### end Alembic commands ###
