"""add forgive amount in emp deduction

Revision ID: 92a114d47418
Revises: bf976f7ee27a
Create Date: 2025-12-04 18:06:57.301851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a114d47418'
down_revision: Union[str, None] = 'bf976f7ee27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_deductions', sa.Column('forgive_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_deductions', 'forgive_amount')
    # ### end Alembic commands ###
