"""add po payment related all tables

Revision ID: 9626ca678dda
Revises: a8f96eb013ed
Create Date: 2025-09-25 15:08:26.823799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9626ca678dda'
down_revision: Union[str, None] = 'a8f96eb013ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po_payments',
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('REGULAR', 'CLOSE', name='paymenttype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_paths', sa.JSON(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_po_payments_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_payments'))
    )
    op.create_index(op.f('ix_po_payments_id'), 'po_payments', ['id'], unique=False)
    op.add_column('purchase_orders', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('purchase_orders', sa.Column('paid_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('purchase_orders', sa.Column('is_closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'is_closed')
    op.drop_column('purchase_orders', 'paid_percentage')
    op.drop_column('purchase_orders', 'paid_amount')
    op.drop_index(op.f('ix_po_payments_id'), table_name='po_payments')
    op.drop_table('po_payments')
    # ### end Alembic commands ###
