"""add offdays table

Revision ID: 96ef1b62248a
Revises: 9fb382877379
Create Date: 2025-09-15 17:40:30.119583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ef1b62248a'
down_revision: Union[str, None] = '9fb382877379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offdays',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('offday_date', sa.Date(), nullable=False),
    sa.Column('offday_type', sa.Enum('WEEKEND', 'PERSONAL_OFFDAY', 'COMPENSATORY_OFF', name='offdaytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_offdays_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offdays'))
    )
    op.create_index(op.f('ix_offdays_id'), 'offdays', ['id'], unique=False)
    op.add_column('attendances', sa.Column('is_weekend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'is_weekend')
    op.drop_index(op.f('ix_offdays_id'), table_name='offdays')
    op.drop_table('offdays')
    # ### end Alembic commands ###
