"""update po filepath column to json

Revision ID: a8f96eb013ed
Revises: 8d8ca6683206
Create Date: 2025-09-22 20:39:45.963897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f96eb013ed'
down_revision: Union[str, None] = '8d8ca6683206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('file_paths', sa.JSON(), nullable=True))
    op.drop_column('purchase_orders', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('purchase_orders', 'file_paths')
    # ### end Alembic commands ###
