"""add location in PO & PO Payment

Revision ID: bf976f7ee27a
Revises: d0c55f63edce
Create Date: 2025-11-24 18:05:35.112089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf976f7ee27a'
down_revision: Union[str, None] = 'd0c55f63edce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('po_payments', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_po_payments_location_id_locations'), 'po_payments', 'locations', ['location_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_purchase_orders_location_id_locations'), 'purchase_orders', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_purchase_orders_location_id_locations'), 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'location_id')
    op.drop_constraint(op.f('fk_po_payments_location_id_locations'), 'po_payments', type_='foreignkey')
    op.drop_column('po_payments', 'location_id')
    # ### end Alembic commands ###
