"""add_fingerprint_table

Revision ID: c33fa4a5d97a
Revises: bc28153e5a21
Create Date: 2025-08-26 15:32:18.908950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33fa4a5d97a'
down_revision: Union[str, None] = 'bc28153e5a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('finger_index', sa.Integer(), nullable=False),
    sa.Column('template_data', sa.LargeBinary(), nullable=False),
    sa.Column('template_hash', sa.String(length=255), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('enrollment_attempts', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('enrolled_by', sa.Integer(), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_fingerprints_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprints')),
    sa.UniqueConstraint('template_hash', name=op.f('uq_fingerprints_template_hash'))
    )
    op.create_index(op.f('ix_fingerprints_id'), 'fingerprints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fingerprints_id'), table_name='fingerprints')
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
