"""add employee to user relation with id

Revision ID: cd38f7b79286
Revises: c33fa4a5d97a
Create Date: 2025-08-27 16:33:47.329472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd38f7b79286'
down_revision: Union[str, None] = 'c33fa4a5d97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('fk_employees_user_id_users'), 'employees', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employees_user_id_users'), 'employees', type_='foreignkey')
    op.alter_column('employees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
