"""add location in user

Revision ID: d0c55f63edce
Revises: 8abf7884fc2a
Create Date: 2025-11-19 12:13:57.345339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c55f63edce'
down_revision: Union[str, None] = '8abf7884fc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_location_id_locations'), 'users', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_location_id_locations'), 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    # ### end Alembic commands ###
