"""update location to goods receipt from item

Revision ID: d1c09da1ee4e
Revises: 9626ca678dda
Create Date: 2025-09-28 15:45:50.650455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c09da1ee4e'
down_revision: Union[str, None] = '9626ca678dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_goods_receipt_items_location_id_locations', 'goods_receipt_items', type_='foreignkey')
    op.drop_column('goods_receipt_items', 'location_id')
    op.add_column('goods_receipts', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_goods_receipts_location_id_locations'), 'goods_receipts', 'locations', ['location_id'], ['id'])
    op.drop_column('goods_receipts', 'delivered_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipts', sa.Column('delivered_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_goods_receipts_location_id_locations'), 'goods_receipts', type_='foreignkey')
    op.drop_column('goods_receipts', 'location_id')
    op.add_column('goods_receipt_items', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_goods_receipt_items_location_id_locations', 'goods_receipt_items', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
