"""add unit type in supplier item

Revision ID: d5edf544850c
Revises: 7065f6665eba
Create Date: 2026-02-02 15:17:50.113206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5edf544850c'
down_revision: Union[str, None] = '7065f6665eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_suppliers', sa.Column('unit_type', sa.Enum('PCS', 'KG', 'G', 'MG', 'L', 'ML', 'M2', 'M3', 'LM', 'CM', 'MM', 'IN', 'BAG', 'BOX', 'CARTON', 'BTL', 'DOZEN', name='unittype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_suppliers', 'unit_type')
    # ### end Alembic commands ###
