"""add approval tables

Revision ID: e9c1362a6105
Revises: c2863fc33cf4
Create Date: 2025-10-12 17:15:41.252989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c1362a6105'
down_revision: Union[str, None] = 'c2863fc33cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_settings',
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_settings'))
    )
    op.create_index(op.f('ix_approval_settings_id'), 'approval_settings', ['id'], unique=False)
    op.create_table('approval_members',
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_approval_members_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_members')),
    sa.UniqueConstraint('module', name=op.f('uq_approval_members_module'))
    )
    op.create_index(op.f('ix_approval_members_id'), 'approval_members', ['id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('request_type', sa.Enum('SHIFT', 'SALARY', 'OFFDAY', name='approvalrequesttype'), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_approval_requests_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_table('approval_responses',
    sa.Column('approval_request_id', sa.Integer(), nullable=False),
    sa.Column('approval_member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalresponsestatus'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_member_id'], ['approval_members.id'], name=op.f('fk_approval_responses_approval_member_id_approval_members')),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_responses_approval_request_id_approval_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_responses'))
    )
    op.create_index(op.f('ix_approval_responses_id'), 'approval_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_responses_id'), table_name='approval_responses')
    op.drop_table('approval_responses')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_members_id'), table_name='approval_members')
    op.drop_table('approval_members')
    op.drop_index(op.f('ix_approval_settings_id'), table_name='approval_settings')
    op.drop_table('approval_settings')
    # ### end Alembic commands ###
