"""add action type in approval member & setting

Revision ID: f5bef56e33e0
Revises: 244d062746c2
Create Date: 2025-10-25 18:41:29.602904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bef56e33e0'
down_revision: Union[str, None] = '244d062746c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_members', sa.Column('action_types', sa.JSON(), nullable=False))
    op.add_column('approval_settings', sa.Column('module', sa.String(length=50), nullable=False))
    op.add_column('approval_settings', sa.Column('action_type', sa.Enum('SHIFT', 'SALARY', 'DAYOFF', 'EMPLOYEE', 'ATTENDANCE', 'EMPLOYEE_DEDUCTION', name='approvalrequesttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_settings', 'action_type')
    op.drop_column('approval_settings', 'module')
    op.drop_column('approval_members', 'action_types')
    # ### end Alembic commands ###
